Revert "Make sample app more similar to others"
This reverts commit 5288a09d4fb2d39f16df04ffa465cdf4caa8d0f7.

Ehh, for some reason I get this weird error:

Error: line is not defined
    at PromisePoolConnection.execute (/Users/hansott/Code/node-RASP/node_modules/mysql2/promise.js:113:22)
    at Cats.all (/Users/hansott/Code/node-RASP/sample-apps/express-mysql2/Cats.js:15:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/hansott/Code/node-RASP/sample-apps/express-mysql2/app.js:62:28

Found this issue but no solutions: https://github.com/sidorares/node-mysql2/issues/1809