Upgrade next sample app to 14.2.33
/home/runner/work/firewall-node/firewall-node/end2end/tests/nextjs-standalone.test.js:17
    throw new Error(`Failed to build: ${stderr.toString()}`);
          ^

Error: Failed to build: Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

    at TAP.<anonymous> (/home/runner/work/firewall-node/firewall-node/end2end/tests/nextjs-standalone.test.js:17:11)
    at Before.#call (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/@tapjs/before/src/index.ts:51:20)
    at Before.before (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/@tapjs/before/src/index.ts:44:17)
    at TAP.before (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/@tapjs/test/test-built/src/index.ts:84:19)
    at Object.<anonymous> (/home/runner/work/firewall-node/firewall-node/end2end/tests/nextjs-standalone.test.js:11:3)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
    at Module._compile (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/pirates/lib/index.js:129:24)
    at node:internal/modules/cjs/loader:1839:10
    at newLoader (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/pirates/lib/index.js:134:7)
    at Object.require.extensions.<computed> (/home/runner/work/firewall-node/firewall-node/end2end/node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/src/index.ts:1358:43)